AllCops:
  Exclude:
    - vendor/**/*
    - config/**/*
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Exclude:
    - db/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - Rakefile

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/*
